/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arnold;

import org.telegram.telegrambots.meta.TelegramBotsApi;
import org.telegram.telegrambots.meta.exceptions.TelegramApiException;
import org.telegram.telegrambots.updatesreceivers.DefaultBotSession;

public class App {
    public static void main(String[] ags) {
        System.out.println("Iniciando Bot ...");
        try {
            TelegramBotsApi botsApi = new TelegramBotsApi(DefaultBotSession.class);
            botsApi.registerBot(new ArnoldBot());
        } catch (TelegramApiException e) {
            e.printStackTrace();
        }
        System.out.println("Rodando ...");
    }
}
